primary.DB_HOST=localhost
primary.DB_PORT=3306
primary.DB_NAME=demo_db
primary.DB_USER=demo_user
primary.DB_TYPE=mysql
primary.DB_PASSWORD_DIR=${ENV_WORK_PATH}/etc/local/pwd
primary.DB_PASSWORD_KEY_FILE=${primary.DB_PASSWORD_DIR}/keyfile
