job.users.DB_PROFILE=primary
job.users.TABLE_NAME=users
job.users.COLUMNS=id,name,email,blog,create_at
job.users.EXPORT_FILE=${ENV_GTP_TEMP_PATH}/00-LENS-${job.users.TABLE_NAME}-${EXPORT_DATE}-2G
job.users.FIELD_SEPARATOR=|!
job.users.LINE_TERMINATOR=@#$\n
job.users.WHERE=create_at between ${YESTERDAY} and ${TODAY}
job.users.COMPRESS.ENABLED=true
job.users.COMPRESS.MODE=gz
job.users.COMPRESS.OVERWRITE=true
job.users.TRANSFER.ENABLED=true
job.users.TRANSFER.DIR=${ENV_EDP_OUT_PATH}
job.users.TRANSFER.MODE=copy
job.users.TRANSFER.OVERWRITE=true
job.users.TRANSFER.RENAME=00-LENS-${job.users.TABLE_NAME}-${EXPORT_DATE}-2G.${job.users.COMPRESS.MODE}
job.users.SPLIT.blog=10000,3
