job.users.DB_TYPE=${ENV_LENS_MNGT_TDSQL_TYPE}
job.users.DB_HOST=${ENV_LENS_MNGT_TDSQL_HOST}
job.users.DB_PORT=${ENV_LENS_MNGT_TDSQL_PORT}
job.users.DB_NAME=${ENV_LENS_MNGT_TDSQL_NAME}
job.users.DB_USER=${ENV_LENS_MNGT_TDSQL_USER}
job.users.DB_PASSWORD_FILE=${ENV_LENS_MNGT_TDSQL_PASSWORD_FILE}
job.users.DB_PASSWORD_KEY_FILE=${ENV_LENS_MNGT_TDSQL_PASSWORD_KEY_FILE}
job.users.TABLE_NAME=users
job.users.COLUMNS=id,name,email,blog,create_at
job.users.EXPORT_FILE=${ENV_GTP_TEMP_PATH}/00-LENS-${job.users.TABLE_NAME}-${EXPORT_DATE}-2G
job.users.FIELD_SEPARATOR=|!
job.users.LINE_TERMINATOR=@#$\n
job.users.FIELD_SEPARATOR_DATA_REPLACEMENT=|?
job.users.WHERE=create_at between ${YESTERDAY} and ${TODAY}
job.users.COMPRESS.ENABLED=true
job.users.COMPRESS.MODE=gz
job.users.COMPRESS.OVERWRITE=true
job.users.TRANSFER.ENABLED=true
job.users.TRANSFER.DIR=${ENV_EDP_OUT_PATH}
job.users.TRANSFER.MODE=copy
job.users.TRANSFER.OVERWRITE=true
job.users.TRANSFER.RENAME=00-LENS-${job.users.TABLE_NAME}-${EXPORT_DATE}-2G.${job.users.COMPRESS.MODE}
job.users.SPLIT.blog=10000,3
