primary.DB_HOST=localhost
primary.DB_PORT=3306
primary.DB_NAME=demo_db
primary.DB_USER=demo_user
primary.DB_TYPE=mysql
primary.DB_PASSWORD_DIR=./script/etc/demo/pwd
primary.DB_PASSWORD_FILE=${primary.DB_PASSWORD_DIR}/${primary.DB_HOST}_${primary.DB_PORT}_${primary.DB_USER}.pwd
primary.DB_PASSWORD_KEY_FILE=./script/etc/demo/pwd/key_file

reporting.DB_HOST=reporting-host
reporting.DB_PORT=5432
reporting.DB_NAME=reporting_db
reporting.DB_USER=report_user
reporting.DB_TYPE=postgres
reporting.DB_PASSWORD_DIR=./script/etc/demo/pwd
reporting.DB_PASSWORD_FILE=${reporting.DB_PASSWORD_DIR}/${reporting.DB_HOST}_${reporting.DB_PORT}_${reporting.DB_USER}.pwd
reporting.DB_PASSWORD_KEY_FILE=./script/etc/demo/pwd/key_file
